version: '3.8'

services:
  guestsense-api:
    build: .
    container_name: guestsense_api
    restart: always
    ports:
      - "80:8000"
    env_file:
      - .env  # This loads my GEMINI_API_KEY
    volumes:
      - .:/app 

